### ISSUE TITLE
Playlist Link Fails

### ISSUE THREAD

**Issue by Shabinder** [cyberboysumanjay/JioSaavnAPI#46]
**Playlist Link:**
`https://www.jiosaavn.com/s/playlist/dc743890bf724e7509bb96a668902396/Hindi_00ss/i4S6We6dWd1ieSJqt9HmOQ`

**StackTrace**
```
192.168.29.235 - - [11/Oct/2021 15:57:10] "GET /playlist/?query=https://www.jiosaavn.com/s/playlist/dc743890bf724e7509bb96a668902396/Hindi_00ss/i4S6We6dWd1ieSJqt9HmOQ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/jiosaavn.py", line 78, in get_playlist_id
    return res.split('"type":"playlist","id":"')[1].split('"')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/app.py", line 69, in playlist
    id = jiosaavn.get_playlist_id(query)
  File "/home/shabinder/PycharmProjects/JioSaavnAPI/jiosaavn.py", line 80, in get_playlist_id
    return res.split('"page_id","')[1].split('","')[0]
IndexError: list index out of range
```

**Comment by cyberboysumanjay** [comment]
Tried this playlist url with the latest build and it is working fine, please feel free to reopen the issue in case again if you're still facing this issue.
