### ISSUE TITLE
API is not working - Can you look into, please

### ISSUE THREAD

**Issue by betamaster8** [cyberboysumanjay/JioSaavnAPI#55]
Hi @cyberboysumanjay 
`http://xxxx/song/?query=https://www.jiosaavn.com/song/jaikal-mahakal/PDIsQyd4XVU`
or use any song URL - the result is same as below for all 

`https://i.imgur.com/C69uA4V.png`

-- updated --

Would be indeed appreciate to release an update to the code #54 #52 💯 
bm

**Comment by betamaster8** [comment]
logcat
@cyberboysumanjay 

`Traceback (most recent call last):
  File ":\\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ":\\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File ":\\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File ":\\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File ":\\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File ":\\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File ":\\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File ":\\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ":\\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File ":\\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ":\\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File ":\\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File ":\\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ":\\JioSaavnAPI\app.py", line 25, in search
    return jsonify(jiosaavn.search_for_song(query,lyrics))
  File ":\\JioSaavnAPI\jiosaavn.py", line 10, in search_for_song
    response = json.loads(response)
  File ":\\Lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File ":\\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ":\\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by cyberboysumanjay** [comment]
Issue is now fixed. Feel free to reopen in case anything isn't working 😄
