### ISSUE TITLE
API not functional - Help please

### ISSUE THREAD

**Issue by betamaster-codes** [cyberboysumanjay/JioSaavnAPI#70]
@cyberboysumanjay 

Hi mate,
Thanks for this project.

The API not working at the moment - can you restore back the functionality please
much appreciated

Cheers
Bm

**Comment by cyberboysumanjay** [comment]
Just checked the build on local and it is working as expected, can you provide some additional details on what exactly you tried and what is the error that you faced?
Feel free to reopen the issue with the details.

**Comment by betamaster-codes** [comment]
Hi @cyberboysumanjay 

Kindly have a look, please
https://i.imgur.com/3cJpZtd.png

Tested on more than 5 win10-22h2 and win11-24h2
missing anything on myside ?- help appreciated

Traceback (most recent call last):
  File "{Drive}:\Python3\JioSaavnAPI\app.py", line 145, in result
    song_id = jiosaavn.get_song_id(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\JioSaavnAPI\jiosaavn.py", line 44, in get_song_id
    res = requests.get(url, data=[('bitrate', '320')])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\Lib\site-packages\requests\sessions.py", line 746, in send
    r.content
  File "{Drive}:\Python3\Lib\site-packages\requests\models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{Drive}:\Python3\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(12823 bytes read, 6410 more expected)', IncompleteRead(12823 bytes read, 6410 more expected))
127.0.0.1 - - [10/Nov/2024 11:21:38] "GET /result/?query=https://www.jiosaavn.com/song/chand-mera-dil-from-amaran-hindi/SCsmVkUGB0AHTTP/1.1" 200 -
127.0.0.1 - - [10/Nov/2024 11:21:38] "GET /favicon.ico HTTP/1.1" 404 -


Cheers
Bm
